name: os_cpu
description: API for CPU information. Works in all platforms, including browsers.
version: 1.0.1
homepage: https://github.com/dint-dev/os

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  os: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3

#dependency_overrides:
#  os:
#    path: ../os